day = input('Digite o Dia que voce nasceu: ')
month = input('Digite o Mes que voce nasceu: ')
year = input('Digite o Ano que voce nasceu: ')
year_old = 2025 - int(year)
print(f'Voce nasceu no dia {day} do mes {month} do ano {year}. Voce tem {year_old} anos.SHOW DE BOLA')
